sudo: required

language: node_js
node_js:
  - "6.9.1"
  - "7.0.0"
  - "7.1.0"

services:
  - docker

script:
  - npm run lint
  - npm test

after_success:
  - 'npm run coveralls'
  
deploy:
  provider: npm
  api_key: "$NPM_API_KEY"
  on:
    branch: build
